"""出站端口：用户风格包持久化与回查（不含 builtin）。"""

from typing import Protocol

from devspace_ai.domain.style_pack.models import StylePack


class StylePackRepositoryPort(Protocol):
    def list_user(self) -> list[StylePack]: ...

    def get(self, id: str) -> StylePack | None: ...

    def create(self, pack: StylePack) -> StylePack: ...

    def update(self, pack: StylePack) -> StylePack | None: ...

    def delete(self, id: str) -> bool: ...

    def count(self) -> int: ...

    def get_by_key(self, key: str) -> StylePack | None: ...
